services:
    backend:
        tty: true
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend/:/backend/
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level trace
        ports:
            - 8000:8000
        container_name: motu_backend

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/usr/src/app
        command: yarn start
        ports:
            - "3000:3000"
        tty: true
        container_name: motu_frontend

    mongo:
        image: mongo:4.0
        networks:
        - mongo_network
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGOUSER
            MONGO_INITDB_ROOT_PASSWORD: $MONGOPASSWORD
        volumes:
        - mongodb_data1:/data/db
        container_name: mongo_server

    mongo-express:
        image: mongo-express
        networks:
        - mongo_network
        restart: always
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: $ADMINUSERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $ADMINPASSWORD
            ME_CONFIG_MONGODB_SERVER: $MONGOSERVER
        depends_on:
        - mongo
    mongo-client:
        image: mongo
        networks:
        - mongo_network
        restart: always
        volumes:
        - mongodb_data2:/data/db
volumes:
  mongodb_data1:
  mongodb_data2:

networks:
  mongo_network: